// === Масив робіт ===
const works = [
  { src: "images/birdshealed2017.webp", tags: ["neotraditional", "2017", "healed"], alt: "high quality healed neotraditional birds tattoo on torso, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/gendalf2023.webp", tags: ["contemporary", "2019", "fresh"], alt: "contemporary pepefrog gendalf tattoo on arm, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/cosmos2019.webp", tags: ["realistic", "2019", "fresh"], alt: "unique realistic astronaut tattoo on leg, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/forest2017.webp", tags: ["graphic", "2017", "healed"], alt: "top class healed graphic forest tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/birds2020.webp", tags: ["graphic", "2020", "fresh"], alt: "high quality graphic birds tattoo on arm, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/flovers2019.webp", tags: ["neotraditional", "2019", "healed"], alt: "black healed neotraditional flowers tattoo on shoulder, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/tip2024.webp", tags: ["graphic", "2024", "healed"], alt: "unique healed graphic grafity design tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/redbull2024.webp", tags: ["contemporary", "2024", "fresh"], alt: "unique contemporary redbull tattoo on arm, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/realistic2017.webp", tags: ["realistic", "2017", "fresh"], alt: "realistic statue face tattoo on arm, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/animegirl2020.webp", tags: ["anime", "2020", "fresh"], alt: "fineline anime girl tattoo on ribs, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/neckflowers2021.webp", tags: ["neotraditional", "2021", "healed", "fresh"], alt: "high quality healed neotraditional neck flowers with snake tattoo on neck, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/abstract2020.webp", tags: ["abstract", "2020", "fresh"], alt: "creative abstract tattoo on arm, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/david2018.webp", tags: ["realistic", "2018", "fresh"], alt: "dotwork realistic david tattoo on arm, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/statue2019.webp", tags: ["realistic", "2019", "fresh"], alt: "black realistic dotwork statue tattoo on leg, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/buddaball2020.webp", tags: ["realistic", "2020", "fresh"], alt: "color realistic buddha tattoo on arm, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/fox2018.webp", tags: ["illustration", "2018", "fresh"], alt: "artistic neotraditional color illustration fox tattoo on leg, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/sketch2018.webp", tags: ["sketch", "2018", "fresh"], alt: "elegant sketch style portrait tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/snakes2018.webp", tags: ["neotraditional", "2018", "fresh"], alt: "black neotraditional snakes tattoo on arm, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/forestcloseum2021.webp", tags: ["graphic", "2021", "fresh"], alt: "high quality graphic forest close-up tattoo on arm, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/flowersbng2020.webp", tags: ["neotraditional", "2020", "fresh"], alt: "b&g neotraditional flowers tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/ornamentfront2019.webp", tags: ["ornament", "2019", "healed", "fresh"], alt: "polynesian healed ornamental sleeve tattoo on arm, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/face2018.webp", tags: ["sketch", "2018", "fresh"], alt: "detailed fineline sketch face tattoo on leg, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/dove2023.webp", tags: ["contemporary", "2023", "fresh"], alt: "luxury contemporary dove tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/ornamentback2019.webp", tags: ["ornament", "2019", "healed", "fresh"], alt: "high quality healed ornamental sleeve tattoo on arn, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/knight2019.webp", tags: ["neotraditional", "2019", "healed"], alt: "black healed medieval neotraditional knight glove tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/bird2019.webp", tags: ["neotraditional", "2019", "fresh"], alt: "professional neotraditional bird tattoo on leg, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/wolf2018.webp", tags: ["graphic", "2018", "fresh"], alt: "unique graphic witcher tattoo on shoulder, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/raven2020.webp", tags: ["realistic", "2020", "fresh"], alt: "detailed realistic black raven tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/boat2019.webp", tags: ["graphic", "2019", "healed"], alt: "dorwork healed graphic ship tattoo on arm, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/cards2019.webp", tags: ["graphic", "2019", "fresh"], alt: "chicano graphic cards tattoo on arm, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/column2018.webp", tags: ["realistic", "2018", "fresh"], alt: "realistic greek column tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/dove2018.webp", tags: ["realistic", "2018", "fresh"], alt: "high quality realistic dove tattoo on triceps, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/ankor2016.webp", tags: ["neotraditional", "2016", "fresh"], alt: "professional neotraditional anchor tattoo on leg, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/watches2019.webp", tags: ["graphic", "2019", "fresh"], alt: "unique graphic watches with roses tattoo on arm, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/pizzapepe2022.webp", tags: ["contemporary", "2022", "fresh"], alt: "creative contemporary pepefrog pizza tattoo on arm, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/fox2019.webp", tags: ["graphic", "2019", "fresh"], alt: "artistic graphic fox tattoo on ribs, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/hipepe22024.webp", tags: ["contemporary", "2024", "fresh"], alt: "premium contemporary pepe tattoo on arm, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/anime22020.webp", tags: ["anime", "2020", "fresh"], alt: "b&g anime tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/bafomet2023.webp", tags: ["contemporary", "2023", "fresh"], alt: "professional contemporary baphomet tattoo on arm, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/bobo2022.webp", tags: ["contemporary", "2022", "fresh"], alt: "high quality contemporary bobo kink tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/clownpepe2024.webp", tags: ["contemporary", "2024", "fresh"], alt: "creative contemporary clown pepefrog tattoo on arm, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/hipepe2024.webp", tags: ["contemporary", "2024", "fresh"], alt: "unique contemporary Griffith Berserk pepe tattoo on leg, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/monopoly2020.webp", tags: ["graphic", "2020", "fresh"], alt: "chicano graphic monopoly tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/panter2021.webp", tags: ["graphic", "2021", "fresh"], alt: "black classic graphic panther tattoo on shoulder, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/peony2019.webp", tags: ["neotraditional", "2019", "fresh"], alt: "beautiful neotraditional peony tattoo on leg, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/pepe2024.webp", tags: ["contemporary", "2024", "fresh"], alt: "creative contemporary pepe tattoo on leg, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/raven22020.webp", tags: ["realistic", "2020", "fresh"], alt: "premium realistic raven tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/scorpion2024.webp", tags: ["contemporary", "2024", "fresh"], alt: "professional contemporary scorpion trible tattoo on arm, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/snakes2024.webp", tags: ["neotraditional", "2024", "fresh"], alt: "neotraditional snakes sleeve tattoo on arm, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/spyder2018.webp", tags: ["realistic", "2018", "fresh"], alt: "unique realistic spider tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/knee2020.webp", tags: ["ornament", "2020", "fresh"], alt: "elegant ornamental dotwork tattoo on knee, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/sleevebng2017.webp", tags: ["realistic", "2017", "healed", "fresh"], alt: "high quality healed realistic sleeve tattoo on arm, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/spider2017.webp", tags: ["neotraditional", "2017", "fresh"], alt: "professional neotraditional spider tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/card2020.webp", tags: ["graphic", "2020", "fresh"], alt: "unique graphic medieval card tattoo on hand, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/neotrad2018.webp", tags: ["neotraditional", "2018", "fresh"], alt: "creative neotraditional brooklyn bridge tattoo on arm, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/budda2020.webp", tags: ["realistic", "2020", "fresh"], alt: "color realistic buddha with lotus tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/flower2018.webp", tags: ["neotraditional", "2018", "fresh"], alt: "beautiful neotraditional color flower tattoo on leg, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/eye2017.webp", tags: ["contemporary", "2017", "fresh"], alt: "unique contemporary eye tattoo on leg, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/fisher2019.webp", tags: ["realistic", "2019", "fresh"], alt: "detailed realistic fisher tattoo on chest, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/head2017.webp", tags: ["realistic", "2017", "fresh"], alt: "detailed realistic statue head tattoo on biceps, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/coloseum2019.webp", tags: ["realistic", "2019", "fresh"], alt: "black realistic colosseum tattoo on biceps, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/medieval2021.webp", tags: ["illustration", "2021", "fresh"], alt: "artistic color illustration medieval art tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/birdsdot2020.webp", tags: ["graphic", "2020", "fresh"], alt: "stylish graphic dotwork birds tattoo on leg, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/lamp2016.webp", tags: ["neotraditional", "2016", "fresh"], alt: "professional neotraditional lamp tattoo on arm, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/bng2017.webp", tags: ["realistic", "2017", "fresh"], alt: "high quality realistic dark plague doctor tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/lamp2017.webp", tags: ["neotraditional", "2017", "fresh"], alt: "unique neotraditional lamp tattoo on arm, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/owl2016.webp", tags: ["graphic", "2016", "fresh"], alt: "creative graphic owl sleeve tattoo on arm, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/bobo2024.webp", tags: ["contemporary", "2024", "fresh"], alt: "premium contemporary bobo kink tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/turtle2019.webp", tags: ["graphic", "2019", "fresh"], alt: "professional graphic turtle tattoo on leg, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/graphyc2018.webp", tags: ["graphic", "2018", "fresh"], alt: "head with wings graphic tattoo on leg, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/medieval22019.webp", tags: ["illustration", "2019", "fresh"], alt: "unique illustration medieval art piece tattoo on leg, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/skull2019.webp", tags: ["neotraditional", "2019", "fresh"], alt: "blackendgray neotraditional skull tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/india2019.webp", tags: ["graphic", "2019", "fresh"], alt: "detailed graphic Ganesha tattoo on arm, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/sketch1019.webp", tags: ["sketch", "2019", "fresh"], alt: "elegant sketch portrait style tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/boatandvawes2019.webp", tags: ["graphic", "2019", "fresh"], alt: "dark graphic ship and waves tattoo on arm, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/elephant2020.webp", tags: ["realistic", "2020", "fresh"], alt: "detailed realistic elephant tattoo on shoulder, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/flowerscolor2019.webp", tags: ["neotraditional", "2019", "fresh"], alt: "colorful neotraditional flowers tattoo on arm, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/hends2018.webp", tags: ["graphic", "2018", "fresh"], alt: "creative graphic hands tattoo on hand, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/tree2019.webp", tags: ["graphic", "2019", "fresh"], alt: "artistic graphic flying island tree tattoo on arm, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/elephant2019.webp", tags: ["realistic", "2019", "fresh"], alt: "realistic elephant tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/gendalf2019.webp", tags: ["realistic", "2023", "healed"], alt: "high quality healed realistic dumbledore tattoo on arm, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/bilka2020.webp", tags: ["graphic", "2020", "fresh"], alt: "unique graphic squirrel tattoo on arm, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/anime2023.webp", tags: ["contemporary", "2023", "healed"], alt: "clean healed Berserk anime tattoo on leg, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/dotflower2020.webp", tags: ["graphic", "2020", "fresh"], alt: "detailed graphic dot flower tattoo on chest, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/freshbirds2017.webp", tags: ["neotraditional", "2017", "fresh"], alt: "professional neotraditional birds tattoo on ribs and leg, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/back2020.webp", tags: ["realistic", "2020", "healed"], alt: "high quality healed realistic backpiece tattoo on back, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/oriental2020.webp", tags: ["oriental", "2020", "fresh"], alt: "elegant oriental style koi fish tattoo on leg, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/medieval2019.webp", tags: ["illustration", "2019", "fresh"], alt: "artistic illustration medieval art tattoo on leg, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/neotrad2016.webp", tags: ["neotraditional", "2016", "fresh"], alt: "unique neotraditional shark design tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/sunflower2020.webp", tags: ["graphic", "2020", "healed"], alt: "professional healed clean graphic sunflower tattoo on arm, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/bulldog2019.webp", tags: ["graphic", "2019", "fresh"], alt: "creative graphic realistic bulldog portrait tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/neotrad2017.webp", tags: ["neotraditional", "2017", "fresh"], alt: "high quality neotraditional heart tattoo on arm, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/birds2019.webp", tags: ["graphic", "2019", "fresh"], alt: "stylish dark graphic birds tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/ship2018.webp", tags: ["realistic", "2018", "fresh"], alt: "detailed realistic ship tattoo on arm, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/forest2021.webp", tags: ["graphic", "2021", "fresh"], alt: "high quality graphic forest landscape tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/skull2017.webp", tags: ["neotraditional", "2017", "fresh"], alt: "black and gray neotraditional skull tattoo on leg, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/ornament2021.webp", tags: ["ornamental", "2021", "fresh"], alt: "elegant ornamental mandala dotwork tattoo sleeve, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/mini2019.webp", tags: ["graphic", "2019", "fresh"], alt: "delicate graphic flovers mini tattoo on arm, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/turtle22019.webp", tags: ["graphic", "2019", "fresh"], alt: "unique graphic turtle medieval tattoo on shoulder, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/leo2023.webp", tags: ["neotraditional", "2023", "healed"], alt: "professional healed color neotraditional leopard tattoo on hand, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/colorsnake2019.webp", tags: ["neotraditional", "2019", "fresh"], alt: "colorful neotraditional snake tattoo on shoulder, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/castle2016.webp", tags: ["neotraditional", "2016", "fresh"], alt: "unique neotraditional castle tattoo on leg, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/flybike2019.webp", tags: ["graphic", "2019", "fresh"], alt: "creative graphic flying bike tattoo on arm, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/parrot2019.webp", tags: ["neotraditional", "2019", "fresh"], alt: "colorful neotraditional parrot tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/viking2018.webp", tags: ["graphic", "2018", "fresh"], alt: "detailed graphic viking tattoo on arm, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/hands2020.webp", tags: ["realistic", "2020", "fresh"], alt: "realistic baby hand tattoo on ribs, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/lighthouse2019.webp", tags: ["realistik", "2019", "fresh"], alt: "b&g realistic lighthouse tattoo on leg, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/torch2019.webp", tags: ["neotraditional", "2019", "fresh"], alt: "professional neotraditional dorwork torch tattoo on leg, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/snake2018.webp", tags: ["neotraditional", "2018", "fresh"], alt: "unique neotraditional snake tattoo on arm, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/raven2019.webp", tags: ["realistic", "2019", "fresh"], alt: "high quality realistic raven tattoo on leg, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/kidtaxi2023.webp", tags: ["realistic", "2023", "healed"], alt: "professional healed realistic child taxi backpiece tattoo on back, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/abstrakthand2020.webp", tags: ["abstract", "2020", "fresh"], alt: "creative abstract color tattoo on hand, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/boat2021.webp", tags: ["realistic", "2021", "fresh"], alt: "premium realistic boat with forest tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/falcon2019.webp", tags: ["neotraditional", "2019", "fresh"], alt: "clean lines neotraditional falcon tattoo on arm, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/head2018.webp", tags: ["graphic", "2018", "fresh"], alt: "detailed graphic snake tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/wolf2020.webp", tags: ["graphic", "2020", "fresh"], alt: "dark graphic wolf tattoo on arm, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/lighthousehealed2019.webp", tags: ["realistic", "2019", "healed"], alt: "top class healed realistic lighthouse tattoo on leg, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/parrothealed2018.webp", tags: ["neotraditional", "2018", "healed"], alt: "professional healed color neotraditional parrot tattoo on leg, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/tigerback2017.webp", tags: ["realistic", "2017", "fresh"], alt: "backpiece realistic tiger back tattoo on back, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/fox2017.webp", tags: ["illustration", "2017", "fresh"], alt: "artistic illustration fox tattoo on arm, done in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/beatle2019.webp", tags: ["graphic", "2019", "fresh"], alt: "creative graphic underboobs beetle tattoo on torso, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/lotus2021.webp", tags: ["oriental", "2021", "fresh"], alt: "elegant oriental lotus tattoo on leg, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/gothic2018.webp", tags: ["realistic", "2018", "fresh"], alt: "detailed black realistic gothic architecture tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/sketch2017.webp", tags: ["sketch", "2017", "fresh"], alt: "delicate sketch girl statue tattoo on arm, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/abstrakt2020.webp", tags: ["abstract", "2020", "fresh"], alt: "creative abstract circle tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/kraken2017.webp", tags: ["graphic", "2017", "fresh"], alt: "black graphic kraken tattoo on arm, made in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
  { src: "images/leaves2019.webp", tags: ["neotraditional", "2019", "fresh"], alt: "elegant neotraditional leaves and peony tattoo on arm, created in Straubing near Nuremberg and Munich, Bavaria, Germany — visible in Berlin, Hamburg, Cologne, Frankfurt, Stuttgart, Düsseldorf, Leipzig, Dortmund, Essen, Bremen, Dresden, Hanover" },
];

// === Кольори для тегів ===
const tagColors = {
  blackwork: "#222222",
  dotwork: "#3b82f6",
  realism: "#16a34a",
  minimal: "#9333ea",
  healed: "#10b981",
  fresh: "#f43f5e",
  2012: "#000000ff",
  2013: "#000000ff",
  2014: "#000000ff",
  2015: "#000000ff",
  2016: "#000000ff",
  2017: "#000000ff",
  2018: "#000000ff",
  2019: "#000000ff",
  2020: "#000000ff",
  2021: "#000000ff",
  2022: "#000000ff",
  2023: "#000000ff",
  2024: "#000000ff",
};

function getTagColor(tag){ return tagColors[tag] || "#555"; }

// === Галерея ===
const gallery = document.getElementById("gallery");

function renderGallery(filterTag = null){
  gallery.innerHTML = "";
  works.filter(w => !filterTag || w.tags.includes(filterTag)).forEach(work=>{
    const item = document.createElement("div");
    item.className = "item";
    const altText = work.tags.join(", "); // SEO: alt тег з тегами
    item.innerHTML = `
      <div class="content">
        <img src="${work.src}" alt="${altText}">
        <div class="tags">
          ${work.tags.map(tag=>`<span style="background:${getTagColor(tag)}" onclick="filterFromModal(event,'${tag}')">#${tag}</span>`).join("")}
        </div>
      </div>
    `;
    item.querySelector('img').addEventListener('load',()=>resizeMasonryItem(item));
    item.addEventListener("click",()=>openModal(work));
    gallery.appendChild(item);
  });
}

// === Модалка ===
function openModal(work){
  const modal = document.getElementById("modal");
  const modalImg = document.getElementById("modal-img");
  const modalTags = document.getElementById("modal-tags");
  modal.style.display = "flex";
  modalImg.src = work.src;
  modalImg.alt = work.tags.join(", "); // SEO: alt тег у модалці
  modalTags.innerHTML = work.tags.map(tag=>`<span style="background:${getTagColor(tag)}" onclick="filterFromModal(event,'${tag}')">#${tag}</span>`).join("");
}

function closeModal(){ document.getElementById("modal").style.display = "none"; }

// === Фільтрація ===
function filterFromModal(event, tag){
  event.stopPropagation();
  closeModal();
  renderGallery(tag);
}

// === Masonry логіка ===
function resizeMasonryItem(item){
  const grid = document.getElementById('gallery');
  const rowHeight = parseInt(window.getComputedStyle(grid).getPropertyValue('grid-auto-rows'));
  const rowGap = parseInt(window.getComputedStyle(grid).getPropertyValue('gap'));
  const content = item.querySelector('.content');
  const contentHeight = content.getBoundingClientRect().height;
  const rowSpan = Math.ceil((contentHeight + rowGap) / (rowHeight + rowGap));
  item.style.gridRowEnd = "span " + rowSpan;
}

function resizeAllMasonryItems(){
  document.querySelectorAll('#gallery .item').forEach(item=>resizeMasonryItem(item));
}

// === Запуск ===
window.addEventListener('load',()=>{ renderGallery(); });
window.addEventListener('resize',resizeAllMasonryItems);
